import java.util.ArrayList;

import tester.*;

public class ASDMap {
  
  Graph graph;
  ArrayList<Vertex> vertexList;
  Vertex vertex1;
  Vertex vertex2;
  Vertex vertex3;
  Vertex vertex4;
  Vertex vertex5;
  Vertex vertex6;
  Vertex vertex7;
  Vertex vertex8;
  Vertex vertex9;
  Vertex vertex10;
  Vertex vertex11;
  Vertex vertex12;
  Vertex vertex13;
  Vertex vertex14;
  Vertex vertex141;
  Vertex vertex15;
  Vertex vertex16;
  Vertex vertex17;
  Vertex vertex18;
  Vertex vertex19;
  Vertex vertex20;
  Vertex vertex21;
  Vertex vertex22;
  Vertex vertex23;
  Vertex vertex24;
  Vertex vertex25;
  Vertex vertex26;
  Vertex vertex27;
  Vertex vertex28;
  Vertex vertex29;
  Vertex vertex30;
  Vertex vertex31;
  Vertex vertex311;
  Vertex vertex32;
  Vertex vertex33;
  Vertex vertex34;
  Vertex vertex35;
  Vertex vertex36;
  Vertex vertex37;
  Vertex vertex38;
  Vertex vertex39;
  Vertex vertex40;
  Vertex vertex41;
  Vertex vertex42;
  Vertex vertex43;
  Vertex vertex44;
  Vertex vertex45;
  Vertex vertex46;
  Vertex vertex47;
  Vertex vertex48;
  Vertex vertex49;
  Vertex vertex50;
  Vertex vertex51;
  Vertex vertex52;
  Vertex vertex53;
  Vertex vertex54;
  Vertex vertex55;
  Vertex vertex56;
  Vertex vertex57;
  Vertex vertex58;
  Vertex vertex59;
  Vertex vertex60;
  Vertex vertex61;
  Vertex vertex62;
  Vertex vertex63;
  Vertex vertex64;
  Vertex vertex65;
  Vertex vertex66;
  Vertex vertex67;
  Vertex vertex68;
  Vertex vertex69;
  Vertex vertex70;
  Vertex vertex71;
  Vertex vertex72;
  Vertex vertex73;
  Vertex vertex74;
  Vertex vertex75;
  Vertex vertex76;
  Vertex vertex77;
  Vertex vertex78;
  Vertex vertex79;
  Vertex vertex80;
  Vertex vertex81;
  Vertex vertex82;
  Vertex vertex83;
  Vertex vertex84;
  Vertex vertex85;
  Vertex vertex86;
  Vertex vertex87;
  Vertex vertex88;
  Vertex vertex89;
  Vertex vertex90;

  
  void init() {
    vertex1 = new Vertex(new ArrayList<Edge>(), 1);
    vertex2 = new Vertex(new ArrayList<Edge>(), 2);
    vertex3 = new Vertex(new ArrayList<Edge>(), 3);
    vertex4 = new Vertex(new ArrayList<Edge>(), 4);
    vertex5 = new Vertex(new ArrayList<Edge>(), 5);
    vertex6 = new Vertex(new ArrayList<Edge>(), 6);
    vertex7 = new Vertex(new ArrayList<Edge>(), 7);
    vertex8 = new Vertex(new ArrayList<Edge>(), 8);
    vertex9 = new Vertex(new ArrayList<Edge>(), 9);
    vertex10 = new Vertex(new ArrayList<Edge>(), 10);
    vertex11 = new Vertex(new ArrayList<Edge>(), 11);
    vertex12 = new Vertex(new ArrayList<Edge>(), 12);
    vertex13 = new Vertex(new ArrayList<Edge>(), 13);
    vertex14 = new Vertex(new ArrayList<Edge>(), 14);
    vertex15 = new Vertex(new ArrayList<Edge>(), 15);
    vertex16 = new Vertex(new ArrayList<Edge>(), 16);
    vertex17 = new Vertex(new ArrayList<Edge>(), 17);
    vertex18 = new Vertex(new ArrayList<Edge>(), 18);
    vertex19 = new Vertex(new ArrayList<Edge>(), 19);
    vertex20 = new Vertex(new ArrayList<Edge>(), 20);
    vertex21 = new Vertex(new ArrayList<Edge>(), 21);
    vertex22 = new Vertex(new ArrayList<Edge>(), 22);
    vertex23 = new Vertex(new ArrayList<Edge>(), 23);
    vertex24 = new Vertex(new ArrayList<Edge>(), 24);
    vertex25 = new Vertex(new ArrayList<Edge>(), 25);
    vertex26 = new Vertex(new ArrayList<Edge>(), 26);
    vertex27 = new Vertex(new ArrayList<Edge>(), 27);
    vertex28 = new Vertex(new ArrayList<Edge>(), 28);
    vertex29 = new Vertex(new ArrayList<Edge>(), 29);
    vertex30 = new Vertex(new ArrayList<Edge>(), 30);
    vertex31 = new Vertex(new ArrayList<Edge>(), 31);
    vertex32 = new Vertex(new ArrayList<Edge>(), 32);
    vertex33 = new Vertex(new ArrayList<Edge>(), 33);
    vertex34 = new Vertex(new ArrayList<Edge>(), 34);
    vertex35 = new Vertex(new ArrayList<Edge>(), 35);
    vertex36 = new Vertex(new ArrayList<Edge>(), 36);
    vertex37 = new Vertex(new ArrayList<Edge>(), 37);
    vertex38 = new Vertex(new ArrayList<Edge>(), 38);
    vertex39 = new Vertex(new ArrayList<Edge>(), 39);
    vertex40 = new Vertex(new ArrayList<Edge>(), 40);
    vertex41 = new Vertex(new ArrayList<Edge>(), 41);
    vertex42 = new Vertex(new ArrayList<Edge>(), 42);
    vertex43 = new Vertex(new ArrayList<Edge>(), 43);
    vertex44 = new Vertex(new ArrayList<Edge>(), 44);
    vertex45 = new Vertex(new ArrayList<Edge>(), 45);
    vertex46 = new Vertex(new ArrayList<Edge>(), 46);
    vertex47 = new Vertex(new ArrayList<Edge>(), 47);
    vertex48 = new Vertex(new ArrayList<Edge>(), 48);
    vertex49 = new Vertex(new ArrayList<Edge>(), 49);
    vertex50 = new Vertex(new ArrayList<Edge>(), 50);
    vertex51 = new Vertex(new ArrayList<Edge>(), 51);
    vertex52 = new Vertex(new ArrayList<Edge>(), 52);
    vertex53 = new Vertex(new ArrayList<Edge>(), 53);
    vertex54 = new Vertex(new ArrayList<Edge>(), 54);
    vertex55 = new Vertex(new ArrayList<Edge>(), 55);
    vertex56 = new Vertex(new ArrayList<Edge>(), 56);
    vertex57 = new Vertex(new ArrayList<Edge>(), 57);
    vertex58 = new Vertex(new ArrayList<Edge>(), 58);
    vertex59 = new Vertex(new ArrayList<Edge>(), 59);
    vertex60 = new Vertex(new ArrayList<Edge>(), 60);
    vertex61 = new Vertex(new ArrayList<Edge>(), 61);
    vertex62 = new Vertex(new ArrayList<Edge>(), 62);
    vertex63 = new Vertex(new ArrayList<Edge>(), 63);
    vertex64 = new Vertex(new ArrayList<Edge>(), 64);
    vertex65 = new Vertex(new ArrayList<Edge>(), 65);
    vertex66 = new Vertex(new ArrayList<Edge>(), 66);
    vertex67 = new Vertex(new ArrayList<Edge>(), 67);
    vertex68 = new Vertex(new ArrayList<Edge>(), 68);
    vertex69 = new Vertex(new ArrayList<Edge>(), 69);
    vertex70 = new Vertex(new ArrayList<Edge>(), 70);
    vertex71 = new Vertex(new ArrayList<Edge>(), 71);
    vertex72 = new Vertex(new ArrayList<Edge>(), 72);
    vertex73 = new Vertex(new ArrayList<Edge>(), 73);
    vertex74 = new Vertex(new ArrayList<Edge>(), 74);
    vertex75 = new Vertex(new ArrayList<Edge>(), 75);
    vertex76 = new Vertex(new ArrayList<Edge>(), 76);
    vertex77 = new Vertex(new ArrayList<Edge>(), 77);
    vertex78 = new Vertex(new ArrayList<Edge>(), 78);
    vertex79 = new Vertex(new ArrayList<Edge>(), 79);
    vertex80 = new Vertex(new ArrayList<Edge>(), 80);
    vertex81 = new Vertex(new ArrayList<Edge>(), 81);
    vertex82 = new Vertex(new ArrayList<Edge>(), 82);
    vertex83 = new Vertex(new ArrayList<Edge>(), 83);
    vertex84 = new Vertex(new ArrayList<Edge>(), 84);
    vertex85 = new Vertex(new ArrayList<Edge>(), 85);
    vertex86 = new Vertex(new ArrayList<Edge>(), 86);
    vertex87 = new Vertex(new ArrayList<Edge>(), 87);
    vertex88 = new Vertex(new ArrayList<Edge>(), 88);
    vertex89 = new Vertex(new ArrayList<Edge>(), 89);
    vertex90 = new Vertex(new ArrayList<Edge>(), 90);
    vertex311 = new Vertex(new ArrayList<Edge>(), 311);
    vertex141 = new Vertex(new ArrayList<Edge>(), 141);

    
    vertex24.outEdges.add(new Edge(vertex24, vertex23));
    vertex25.outEdges.add(new Edge(vertex25, vertex23));
    vertex25.outEdges.add(new Edge(vertex25, vertex26));
    vertex26.outEdges.add(new Edge(vertex26, vertex19));
    vertex26.outEdges.add(new Edge(vertex26, vertex27));
    vertex26.outEdges.add(new Edge(vertex26, vertex25));
    vertex26.outEdges.add(new Edge(vertex26, vertex28));
    vertex27.outEdges.add(new Edge(vertex27, vertex88));
    vertex27.outEdges.add(new Edge(vertex27, vertex26));
    vertex20.outEdges.add(new Edge(vertex20, vertex21));
    vertex20.outEdges.add(new Edge(vertex20, vertex19));
    vertex20.outEdges.add(new Edge(vertex20, vertex22));
    vertex21.outEdges.add(new Edge(vertex21, vertex3));
    vertex21.outEdges.add(new Edge(vertex21, vertex21));
    vertex21.outEdges.add(new Edge(vertex21, vertex22));
    vertex22.outEdges.add(new Edge(vertex22, vertex21));
    vertex22.outEdges.add(new Edge(vertex22, vertex20));
    vertex22.outEdges.add(new Edge(vertex22, vertex23));
    vertex23.outEdges.add(new Edge(vertex23, vertex22));
    vertex23.outEdges.add(new Edge(vertex23, vertex31));
    vertex23.outEdges.add(new Edge(vertex23, vertex25));
    vertex23.outEdges.add(new Edge(vertex23, vertex24));
    vertex28.outEdges.add(new Edge(vertex28, vertex26));
    vertex28.outEdges.add(new Edge(vertex28, vertex29));
    vertex28.outEdges.add(new Edge(vertex28, vertex33));
    vertex29.outEdges.add(new Edge(vertex29, vertex28));
    vertex29.outEdges.add(new Edge(vertex29, vertex39));
    vertex4.outEdges.add(new Edge(vertex4, vertex5));
    vertex8.outEdges.add(new Edge(vertex8, vertex7));
    vertex59.outEdges.add(new Edge(vertex59, vertex60));
    vertex59.outEdges.add(new Edge(vertex59, vertex58));
    vertex58.outEdges.add(new Edge(vertex58, vertex57));
    vertex58.outEdges.add(new Edge(vertex58, vertex54));
    vertex58.outEdges.add(new Edge(vertex58, vertex59));
    vertex58.outEdges.add(new Edge(vertex58, vertex60));
    vertex55.outEdges.add(new Edge(vertex55, vertex53));
    vertex55.outEdges.add(new Edge(vertex55, vertex56));
    vertex54.outEdges.add(new Edge(vertex54, vertex53));
    vertex54.outEdges.add(new Edge(vertex54, vertex58));
    vertex57.outEdges.add(new Edge(vertex57, vertex56));
    vertex57.outEdges.add(new Edge(vertex57, vertex58));
    vertex57.outEdges.add(new Edge(vertex57, vertex76));
    vertex56.outEdges.add(new Edge(vertex56, vertex57));
    vertex56.outEdges.add(new Edge(vertex56, vertex55));
    vertex51.outEdges.add(new Edge(vertex51, vertex50));
    vertex51.outEdges.add(new Edge(vertex51, vertex49));
    vertex51.outEdges.add(new Edge(vertex51, vertex52));
    vertex50.outEdges.add(new Edge(vertex50, vertex49));
    vertex50.outEdges.add(new Edge(vertex50, vertex51));
    vertex53.outEdges.add(new Edge(vertex53, vertex52));
    vertex53.outEdges.add(new Edge(vertex53, vertex55));
    vertex53.outEdges.add(new Edge(vertex53, vertex54));
    vertex52.outEdges.add(new Edge(vertex52, vertex51));
    vertex52.outEdges.add(new Edge(vertex52, vertex53));
    vertex311.outEdges.add(new Edge(vertex311, vertex30));
    vertex311.outEdges.add(new Edge(vertex311, vertex36));
    vertex88.outEdges.add(new Edge(vertex88, vertex86));
    vertex88.outEdges.add(new Edge(vertex88, vertex89));
    vertex88.outEdges.add(new Edge(vertex88, vertex27));
    vertex89.outEdges.add(new Edge(vertex89, vertex90));
    vertex89.outEdges.add(new Edge(vertex89, vertex88));
    vertex82.outEdges.add(new Edge(vertex82, vertex81));
    vertex82.outEdges.add(new Edge(vertex82, vertex71));
    vertex82.outEdges.add(new Edge(vertex82, vertex83));
    vertex83.outEdges.add(new Edge(vertex83, vertex82));
    vertex83.outEdges.add(new Edge(vertex83, vertex34));
    vertex83.outEdges.add(new Edge(vertex83, vertex35));
    vertex80.outEdges.add(new Edge(vertex80, vertex79));
    vertex80.outEdges.add(new Edge(vertex80, vertex78));
    vertex80.outEdges.add(new Edge(vertex80, vertex81));
    vertex80.outEdges.add(new Edge(vertex80, vertex85));
    vertex81.outEdges.add(new Edge(vertex81, vertex80));
    vertex81.outEdges.add(new Edge(vertex81, vertex82));
    vertex86.outEdges.add(new Edge(vertex86, vertex85));
    vertex86.outEdges.add(new Edge(vertex86, vertex87));
    vertex86.outEdges.add(new Edge(vertex86, vertex88));
    vertex87.outEdges.add(new Edge(vertex87, vertex86));
    vertex84.outEdges.add(new Edge(vertex84, vertex80));
    vertex84.outEdges.add(new Edge(vertex84, vertex85));
    vertex85.outEdges.add(new Edge(vertex85, vertex84));
    vertex85.outEdges.add(new Edge(vertex85, vertex34));
    vertex85.outEdges.add(new Edge(vertex85, vertex80));
    vertex85.outEdges.add(new Edge(vertex85, vertex86));
    vertex3.outEdges.add(new Edge(vertex3, vertex2));
    vertex3.outEdges.add(new Edge(vertex3, vertex5));
    vertex3.outEdges.add(new Edge(vertex3, vertex21));
    vertex7.outEdges.add(new Edge(vertex7, vertex6));
    vertex7.outEdges.add(new Edge(vertex7, vertex8));
    vertex7.outEdges.add(new Edge(vertex7, vertex9));
    vertex39.outEdges.add(new Edge(vertex39, vertex38));
    vertex39.outEdges.add(new Edge(vertex39, vertex69));
    vertex38.outEdges.add(new Edge(vertex38, vertex37));
    vertex38.outEdges.add(new Edge(vertex38, vertex40));
    vertex38.outEdges.add(new Edge(vertex38, vertex39));
    vertex33.outEdges.add(new Edge(vertex33, vertex28));
    vertex33.outEdges.add(new Edge(vertex33, vertex34));
    vertex32.outEdges.add(new Edge(vertex32, vertex30));
    vertex32.outEdges.add(new Edge(vertex32, vertex34));
    vertex31.outEdges.add(new Edge(vertex31, vertex23));
    vertex31.outEdges.add(new Edge(vertex31, vertex30));
    vertex30.outEdges.add(new Edge(vertex30, vertex31));
    vertex30.outEdges.add(new Edge(vertex30, vertex311));
    vertex30.outEdges.add(new Edge(vertex30, vertex32));
    vertex30.outEdges.add(new Edge(vertex30, vertex35));
    vertex30.outEdges.add(new Edge(vertex30, vertex29));
    vertex37.outEdges.add(new Edge(vertex37, vertex36));
    vertex37.outEdges.add(new Edge(vertex37, vertex38));
    vertex36.outEdges.add(new Edge(vertex36, vertex35));
    vertex36.outEdges.add(new Edge(vertex36, vertex31));
    vertex36.outEdges.add(new Edge(vertex36, vertex37));
    vertex35.outEdges.add(new Edge(vertex35, vertex30));
    vertex35.outEdges.add(new Edge(vertex35, vertex36));
    vertex35.outEdges.add(new Edge(vertex35, vertex34));
    vertex35.outEdges.add(new Edge(vertex35, vertex83));
    vertex34.outEdges.add(new Edge(vertex34, vertex33));
    vertex34.outEdges.add(new Edge(vertex34, vertex32));
    vertex34.outEdges.add(new Edge(vertex34, vertex85));
    vertex34.outEdges.add(new Edge(vertex34, vertex83));
    vertex34.outEdges.add(new Edge(vertex34, vertex35));
    vertex60.outEdges.add(new Edge(vertex60, vertex61));
    vertex60.outEdges.add(new Edge(vertex60, vertex58));
    vertex60.outEdges.add(new Edge(vertex60, vertex59));
    vertex60.outEdges.add(new Edge(vertex60, vertex63));
    vertex61.outEdges.add(new Edge(vertex61, vertex60));
    vertex61.outEdges.add(new Edge(vertex61, vertex44));
    vertex62.outEdges.add(new Edge(vertex62, vertex64));
    vertex62.outEdges.add(new Edge(vertex62, vertex43));
    vertex63.outEdges.add(new Edge(vertex63, vertex62));
    vertex63.outEdges.add(new Edge(vertex63, vertex63));
    vertex63.outEdges.add(new Edge(vertex63, vertex60));
    vertex64.outEdges.add(new Edge(vertex64, vertex63));
    vertex64.outEdges.add(new Edge(vertex64, vertex65));
    vertex65.outEdges.add(new Edge(vertex65, vertex66));
    vertex65.outEdges.add(new Edge(vertex65, vertex64));
    vertex65.outEdges.add(new Edge(vertex65, vertex68));
    vertex66.outEdges.add(new Edge(vertex66, vertex67));
    vertex66.outEdges.add(new Edge(vertex66, vertex65));
    vertex66.outEdges.add(new Edge(vertex66, vertex41));
    vertex67.outEdges.add(new Edge(vertex67, vertex41));
    vertex67.outEdges.add(new Edge(vertex67, vertex66));
    vertex68.outEdges.add(new Edge(vertex68, vertex65));
    vertex68.outEdges.add(new Edge(vertex68, vertex70));
    vertex68.outEdges.add(new Edge(vertex68, vertex69));
    vertex68.outEdges.add(new Edge(vertex68, vertex71));
    vertex69.outEdges.add(new Edge(vertex69, vertex68));
    vertex69.outEdges.add(new Edge(vertex69, vertex39));
    vertex69.outEdges.add(new Edge(vertex69, vertex70));
    vertex69.outEdges.add(new Edge(vertex69, vertex40));
    vertex2.outEdges.add(new Edge(vertex2, vertex1));
    vertex2.outEdges.add(new Edge(vertex2, vertex3));
    vertex6.outEdges.add(new Edge(vertex6, vertex5));
    vertex6.outEdges.add(new Edge(vertex6, vertex7));
    vertex90.outEdges.add(new Edge(vertex90, vertex17));
    vertex90.outEdges.add(new Edge(vertex90, vertex89));
    vertex11.outEdges.add(new Edge(vertex11, vertex9));
    vertex11.outEdges.add(new Edge(vertex11, vertex12));
    vertex11.outEdges.add(new Edge(vertex11, vertex18));
    vertex10.outEdges.add(new Edge(vertex10, vertex9));
    vertex13.outEdges.add(new Edge(vertex13, vertex141));
    vertex13.outEdges.add(new Edge(vertex13, vertex14));
    vertex13.outEdges.add(new Edge(vertex13, vertex12));
    vertex12.outEdges.add(new Edge(vertex12, vertex11));
    vertex12.outEdges.add(new Edge(vertex12, vertex13));
    vertex15.outEdges.add(new Edge(vertex15, vertex14));
    vertex15.outEdges.add(new Edge(vertex15, vertex16));
    vertex14.outEdges.add(new Edge(vertex14, vertex13));
    vertex14.outEdges.add(new Edge(vertex14, vertex15));
    vertex17.outEdges.add(new Edge(vertex17, vertex18));
    vertex17.outEdges.add(new Edge(vertex17, vertex16));
    vertex17.outEdges.add(new Edge(vertex17, vertex90));
    vertex16.outEdges.add(new Edge(vertex16, vertex15));
    vertex16.outEdges.add(new Edge(vertex16, vertex17));
    vertex19.outEdges.add(new Edge(vertex19, vertex18));
    vertex19.outEdges.add(new Edge(vertex19, vertex26));
    vertex19.outEdges.add(new Edge(vertex19, vertex20));
    vertex18.outEdges.add(new Edge(vertex18, vertex11));
    vertex18.outEdges.add(new Edge(vertex18, vertex17));
    vertex18.outEdges.add(new Edge(vertex18, vertex19));
    vertex48.outEdges.add(new Edge(vertex48, vertex47));
    vertex49.outEdges.add(new Edge(vertex49, vertex45));
    vertex49.outEdges.add(new Edge(vertex49, vertex51));
    vertex49.outEdges.add(new Edge(vertex49, vertex50));
    vertex46.outEdges.add(new Edge(vertex46, vertex45));
    vertex46.outEdges.add(new Edge(vertex46, vertex47));
    vertex47.outEdges.add(new Edge(vertex47, vertex46));
    vertex47.outEdges.add(new Edge(vertex47, vertex48));
    vertex44.outEdges.add(new Edge(vertex44, vertex43));
    vertex44.outEdges.add(new Edge(vertex44, vertex45));
    vertex44.outEdges.add(new Edge(vertex44, vertex61));
    vertex45.outEdges.add(new Edge(vertex45, vertex46));
    vertex45.outEdges.add(new Edge(vertex45, vertex44));
    vertex45.outEdges.add(new Edge(vertex45, vertex49));
    vertex42.outEdges.add(new Edge(vertex42, vertex41));
    vertex42.outEdges.add(new Edge(vertex42, vertex43));
    vertex43.outEdges.add(new Edge(vertex43, vertex42));
    vertex43.outEdges.add(new Edge(vertex43, vertex44));
    vertex43.outEdges.add(new Edge(vertex43, vertex62));
    vertex40.outEdges.add(new Edge(vertex40, vertex38));
    vertex40.outEdges.add(new Edge(vertex40, vertex69));
    vertex40.outEdges.add(new Edge(vertex40, vertex41));
    vertex41.outEdges.add(new Edge(vertex41, vertex40));
    vertex41.outEdges.add(new Edge(vertex41, vertex42));
    vertex41.outEdges.add(new Edge(vertex41, vertex67));
    vertex41.outEdges.add(new Edge(vertex41, vertex66));
    vertex1.outEdges.add(new Edge(vertex1, vertex2));
    vertex5.outEdges.add(new Edge(vertex5, vertex4));
    vertex5.outEdges.add(new Edge(vertex5, vertex3));
    vertex5.outEdges.add(new Edge(vertex5, vertex6));
    vertex9.outEdges.add(new Edge(vertex9, vertex7));
    vertex9.outEdges.add(new Edge(vertex9, vertex10));
    vertex9.outEdges.add(new Edge(vertex9, vertex11));
    vertex141.outEdges.add(new Edge(vertex141, vertex13));
    vertex77.outEdges.add(new Edge(vertex77, vertex75));
    vertex76.outEdges.add(new Edge(vertex76, vertex75));
    vertex76.outEdges.add(new Edge(vertex76, vertex57));
    vertex75.outEdges.add(new Edge(vertex75, vertex77));
    vertex75.outEdges.add(new Edge(vertex75, vertex76));
    vertex75.outEdges.add(new Edge(vertex75, vertex74));
    vertex74.outEdges.add(new Edge(vertex74, vertex73));
    vertex74.outEdges.add(new Edge(vertex74, vertex75));
    vertex74.outEdges.add(new Edge(vertex74, vertex78));
    vertex73.outEdges.add(new Edge(vertex73, vertex72));
    vertex73.outEdges.add(new Edge(vertex73, vertex74));
    vertex72.outEdges.add(new Edge(vertex72, vertex71));
    vertex72.outEdges.add(new Edge(vertex72, vertex73));
    vertex71.outEdges.add(new Edge(vertex71, vertex68));
    vertex71.outEdges.add(new Edge(vertex71, vertex72));
    vertex71.outEdges.add(new Edge(vertex71, vertex82));
    vertex70.outEdges.add(new Edge(vertex70, vertex69));
    vertex70.outEdges.add(new Edge(vertex70, vertex68));
    vertex79.outEdges.add(new Edge(vertex79, vertex78));
    vertex79.outEdges.add(new Edge(vertex79, vertex80));
    vertex78.outEdges.add(new Edge(vertex78, vertex74));
    vertex78.outEdges.add(new Edge(vertex78, vertex80));
    vertex78.outEdges.add(new Edge(vertex78, vertex79));
    
    vertexList = new ArrayList<Vertex>();
    vertexList.add(vertex1);
    vertexList.add(vertex2);
    vertexList.add(vertex3);
    vertexList.add(vertex4);
    vertexList.add(vertex5);
    vertexList.add(vertex6);
    vertexList.add(vertex7);
    vertexList.add(vertex8);
    vertexList.add(vertex9);
    vertexList.add(vertex10);
    vertexList.add(vertex11);
    vertexList.add(vertex12);
    vertexList.add(vertex13);
    vertexList.add(vertex14);
    vertexList.add(vertex15);
    vertexList.add(vertex16);
    vertexList.add(vertex17);
    vertexList.add(vertex18);
    vertexList.add(vertex19);
    vertexList.add(vertex20);
    vertexList.add(vertex21);
    vertexList.add(vertex22);
    vertexList.add(vertex23);
    vertexList.add(vertex24);
    vertexList.add(vertex25);
    vertexList.add(vertex26);
    vertexList.add(vertex27);
    vertexList.add(vertex28);
    vertexList.add(vertex29);
    vertexList.add(vertex30);
    vertexList.add(vertex31);
    vertexList.add(vertex32);
    vertexList.add(vertex33);
    vertexList.add(vertex34);
    vertexList.add(vertex35);
    vertexList.add(vertex36);
    vertexList.add(vertex37);
    vertexList.add(vertex38);
    vertexList.add(vertex39);
    vertexList.add(vertex40);
    vertexList.add(vertex41);
    vertexList.add(vertex42);
    vertexList.add(vertex43);
    vertexList.add(vertex44);
    vertexList.add(vertex45);
    vertexList.add(vertex46);
    vertexList.add(vertex47);
    vertexList.add(vertex48);
    vertexList.add(vertex49);
    vertexList.add(vertex50);
    vertexList.add(vertex51);
    vertexList.add(vertex52);
    vertexList.add(vertex53);
    vertexList.add(vertex54);
    vertexList.add(vertex55);
    vertexList.add(vertex56);
    vertexList.add(vertex57);
    vertexList.add(vertex58);
    vertexList.add(vertex59);
    vertexList.add(vertex60);
    vertexList.add(vertex61);
    vertexList.add(vertex62);
    vertexList.add(vertex63);
    vertexList.add(vertex64);
    vertexList.add(vertex65);
    vertexList.add(vertex66);
    vertexList.add(vertex67);
    vertexList.add(vertex68);
    vertexList.add(vertex69);
    vertexList.add(vertex70);
    vertexList.add(vertex71);
    vertexList.add(vertex72);
    vertexList.add(vertex73);
    vertexList.add(vertex74);
    vertexList.add(vertex75);
    vertexList.add(vertex76);
    vertexList.add(vertex77);
    vertexList.add(vertex78);
    vertexList.add(vertex79);
    vertexList.add(vertex80);
    vertexList.add(vertex81);
    vertexList.add(vertex82);
    vertexList.add(vertex83);
    vertexList.add(vertex84);
    vertexList.add(vertex85);
    vertexList.add(vertex86);
    vertexList.add(vertex87);
    vertexList.add(vertex88);
    vertexList.add(vertex89);
    vertexList.add(vertex90);
    vertexList.add(vertex311);
    vertexList.add(vertex141);

    graph = new Graph(vertexList);
  }
  
  void testPath(Tester t) {
    init();
    ArrayList<Vertex> vs = graph.pathBetween(vertex1, vertex87, new Queue<Vertex>());
    for (Vertex v: vs) {
      System.out.println(v.id);
    }
    
    return;
  }
}
